import torch
import torchaudio
import numpy as np


keep_genre_cols_names = ['electronic___abstract', 'electronic___acid',
       'electronic___acid_house', 'electronic___bassline',
       'electronic___berlin_school', 'electronic___big_beat',
       'electronic___breakbeat', 'electronic___breakcore',
       'electronic___breaks', 'electronic___dance_pop',
       'electronic___deep_house', 'electronic___deep_techno',
       'electronic___disco', 'electronic___disco_polo',
       'electronic___downtempo', 'electronic___dub',
       'electronic___dub_techno', 'electronic___ebm',
       'electronic___electro', 'electronic___electro_house',
       'electronic___electroclash', 'electronic___euro_house',
       'electronic___euro_disco', 'electronic___eurobeat',
       'electronic___eurodance', 'electronic___experimental',
       'electronic___garage_house', 'electronic___ghetto',
       'electronic___ghetto_house', 'electronic___halftime',
       'electronic___hands_up', 'electronic___hard_house',
       'electronic___hard_techno', 'electronic___hardcore',
       'electronic___hardstyle', 'electronic___hi_nrg',
       'electronic___hip_hop', 'electronic___hip_house',
       'electronic___house', 'electronic___idm',
       'electronic___industrial', 'electronic___italo_house',
       'electronic___italo_disco', 'electronic___italodance',
       'electronic___juke', 'electronic___jumpstyle',
       'electronic___latin', 'electronic___minimal',
       'electronic___minimal_techno', 'electronic___new_age',
       'electronic___new_beat', 'electronic___new_wave',
       'electronic___nu_disco', 'electronic___progressive_house',
       'electronic___rhythmic_noise', 'electronic___synth_pop',
       'electronic___synthwave', 'electronic___tech_house',
       'electronic___techno', 'electronic___tribal',
       'electronic___tribal_house', 'electronic___tropical_house',
       'electronic___uk_garage', 'electronic___vaporwave',
       'folk_world__country___african',
       'folk_world__country___canzone_napoletana',
       'folk_world__country___catalan_music',
       'folk_world__country___flamenco', 'folk_world__country___folk',
       'folk_world__country___highlife',
       'folk_world__country___hindustani',
       'folk_world__country___honky_tonk',
       'folk_world__country___soukous', 'folk_world__country___séga',
       'folk_world__country___zouk', 'funk__soul___afrobeat',
       'funk__soul___boogie', 'funk__soul___contemporary_rb',
       'funk__soul___disco', 'funk__soul___free_funk',
       'funk__soul___funk', 'funk__soul___neo_soul',
       'funk__soul___new_jack_swing', 'funk__soul___p.funk',
       'funk__soul___psychedelic', 'funk__soul___rhythm__blues',
       'funk__soul___soul', 'funk__soul___uk_street_soul',
       'jazz___afrobeat', 'jazz___bossa_nova', 'latin___afro_cuban',
       'latin___batucada', 'latin___beguine', 'latin___bolero',
       'latin___boogaloo', 'latin___bossanova', 'latin___cha_cha',
       'latin___compas', 'latin___cubano', 'latin___cumbia',
       'latin___forró', 'latin___guajira', 'latin___guaracha',
       'latin___mpb', 'latin___mambo', 'latin___pachanga',
       'latin___porro', 'latin___ranchera', 'latin___reggaeton',
       'latin___rumba', 'latin___salsa', 'latin___samba', 'latin___son',
       'pop___bubblegum', 'pop___city_pop', 'pop___europop',
       'pop___indie_pop', 'pop___j_pop', 'reggae___calypso',
       'reggae___dancehall', 'reggae___dub', 'reggae___lovers_rock',
       'reggae___ragga', 'reggae___reggae', 'reggae___reggae_pop',
       'reggae___rocksteady', 'reggae___roots_reggae', 'reggae___soca',
       'latin___baião']

keep_genre_cols_indices = [31,
 32,
 33,
 36,
 38,
 39,
 41,
 42,
 43,
 47,
 50,
 51,
 52,
 53,
 55,
 58,
 59,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 74,
 75,
 76,
 80,
 81,
 83,
 84,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 94,
 95,
 96,
 97,
 99,
 100,
 102,
 105,
 106,
 110,
 111,
 112,
 114,
 117,
 120,
 125,
 126,
 127,
 129,
 131,
 132,
 134,
 135,
 136,
 137,
 140,
 141,
 145,
 146,
 148,
 150,
 151,
 159,
 160,
 162,
 164,
 165,
 166,
 167,
 168,
 169,
 171,
 172,
 173,
 174,
 175,
 176,
 178,
 206,
 210,
 230,
 232,
 233,
 234,
 235,
 236,
 237,
 239,
 240,
 241,
 243,
 245,
 246,
 247,
 248,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 280,
 282,
 283,
 284,
 285,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 304,
 231]


keep_gcol_dict = dict(zip(keep_genre_cols_indices, keep_genre_cols_names))


def load_mono_16k_tensor(path: str, target_len: int = 30,
                         return_shape: str = "bct") -> torch.Tensor:
    """
    Load audio as torch tensor and return either:
      - 'bct' -> [B=1, C=1, T]  (most ONNX/PyTorch encoders)
      - 'bt'  -> [B=1, T]      (if your lib expects (B,T))
    """
    wav, sr = torchaudio.load(path) 
    SR = 16000
    if wav.shape[0] > 1:
        wav = wav.mean(dim=0, keepdim=True)  # [1, T] mono
    if sr != 16000:
        wav = torchaudio.transforms.Resample(orig_freq=sr, new_freq=SR)(wav)  # [1, T']
    wav = wav.to(torch.float32)
    l = wav.shape[1]
    div = l//(SR*target_len)
    slic = div*SR*target_len
    wav = wav[:, :slic]
    data = wav.reshape(-1, SR*target_len)
    return data