name: Project Tools Testing


on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7"]
        
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install numpy
          pip install inflect
          pip install tqdm
          pip install -e .
      - name: Test with pytest
        run: pytest tests/
